### PR TITLE
Fix properties

### PR DESCRIPTION
**Pull request by andreas-schilling**

### CODE REVIEW

**Comment by andreas-schilling** [comment]
Argh, fucked this up. Simply decline if you want me to redo this :-/

**Comment by rwinch** [comment]
@andreas-schilling Not a problem. Try doing this:

```
git checkout fix-properties # ensure you are in the correct branch
git reset --hard origin/master # make it so there are no changes
git checkout andreas-schilling/fix-properties gradle.properties # get the value for gradle.properties from the remote branch
git commit -m 'Fix gradle properties' # Save only those changes
git push -f andreas-schilling fix-properties # force pushing to your branch updates this PR
```

If you have trouble/questions, feel free to ping me.

**Comment by andreas-schilling** [comment]
Ping? :)

**Comment by rwinch** [comment]
Thanks for the ping @andreas-schilling This is now merged. I went ahead and did a polish commit that removed the additional whitespace too 622ce405f98d47f007218895cbc5cbd59a4cc6af

**Pull request merged**
